SYSTEM:
  SKIP_STEPS: False
  FILENAME_PREFIX: "generic_prefix"

FILENAMES:
  INPUT_FILENAME: "generic_filename"

PRIVATE_FOLDER_PATHS:
  INPUT_FOLDER: "input"
  OUTPUT_FOLDER: "output"

LOGGER:
  DEFAULT_LOG_LEVEL: 10
  FORCE_DEFAULT_LOG_LEVEL_FOR_WHOLE_PROGRAM: False